-- Database Client dump 8.0.9
-- Host: 127.0.0.1 Database: null

DROP TABLE IF EXISTS menus;
CREATE TABLE menus (
menu_id INTEGER NOT NULL, 
name VARCHAR NOT NULL, 
description VARCHAR NOT NULL, 
price FLOAT NOT NULL, 
stock_quantity INTEGER, 
status VARCHAR NOT NULL, 
menu_url VARCHAR NOT NULL, 
category_id INTEGER NOT NULL, 
PRIMARY KEY (menu_id), 
FOREIGN KEY(category_id) REFERENCES categories (category_id)
);
INSERT INTO menus(menu_id,name,description,price,stock_quantity,status,menu_url,category_id) VALUES(1,'Afang','Description: This rich and nutritious soup is made with a combination of finely chopped Afang (Okazi) leaves and waterleaf
',500,50,'Available ','images/afang-1734385317832.png',1),(2,'Egusi','Lorem ipsum dolor sit amet. Qui autem dolor eum impedit rerum ut vitae molestias et blanditiis tempora aut consequatur c...',500,50,'Available','images/egusi-1734385453822.png',1),(3,'Goat Meat','Voluptates qui quia totam est eius dolor. Et voluptatum dolor eum deleniti nulla et sunt voluptatem vel rerum earum et i...',800,80,'Available','images/goat_meat-1734385640750.png',4),(4,'Amala Fufu','Aenean non nulla a nibh pellentesque dapibus eget facilisis est. Nullam placerat blandit massa, nec consectetur magna al...',250,30,'Available ','images/amala-1734385759455.jpg',2),(5,'Okoro Soup','Curabitur varius, diam nec accumsan congue, purus ex malesuada est, vel tempor mauris lacus a velit. Ut et neque ornare ...',600,45,'Available','images/Okro-Soup-1734385874307.jpg',1),(6,'Cow Legs','Cum suscipit iure ab dolores omnis qui dolor animi? Ut vitae amet id molestiae voluptas aut minima obcaecati et tempore ...',800,60,'Available','images/cow_leg-1734436661246.png',4),(7,'Momoi','This rich and nutritious soup is made with a combination of finely chopped Afang (Okazi) leaves and waterleaf...

',500,20,'Available ','images/moimoi-1734436751499.png',3),(8,'Fried Rice','Ut necessitatibus commodi At illo soluta eum tempora quaerat. Et fuga quibusdam qui suscipit earum...',700,45,'Available','images/fried_rice-1734436816743.png',5),(9,'Ogbonno Soup','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vel finibus neque. Vestibulum pellentesque sollicitudin l...',649,30,'Available ','images/ogbonno_soup-1734436867842.jpg',1),(10,'Banga Soup','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla vitae enim varius, auctor ...',850,30,'Available ','images/banga_soup-1734436972931.png',1),(11,'Ewedu Soup','Mauris gravida, erat vitae rhoncus vulputate, dui orci fringilla lacus, suscipit fermentum erat dui vitae felis. Donec e...',600,37,'Available ','images/ewedu_soup-1734437086130.jpg',1),(12,'Oha Soup','Sed ornare ipsum aliquam, gravida eros sit amet, euismod purus. Proin non mauris eget lectus tincidunt sollicitudin. Pra...',700,30,'Available ','images/Oha-Soup-1734437349868.jpg',1),(13,'Pounded Yam Fufu','Cras pulvinar ex est, tincidunt varius metus ultricies eget. Morbi cursus enim vitae orci luctus pharetra quis et lectus...',300,20,'Available ','images/pounded_yam-1734437441497.png',1),(14,'Semovita Fufu','Nam egestas egestas tortor sit amet fermentum. Aenean iaculis porta erat. Suspendisse vel facilisis ligula. Donec dapibu...',250,40,'Available','images/seovita-1734437524565.jpg',2),(15,'Wheat Fufu','Pellentesque sed posuere urna. Vivamus maximus, mi non auctor convallis, neque magna efficitur elit, ac aliquam orci en...',300,30,'Available','images/wheat-1734437568971.jpg',2),(16,'Eba Fufu','Phasellus sit amet sem vel erat tristique blandit. Quisque sagittis leo velit, in consectetur velit viverra vitae. Fusce...',250,50,'Available ','images/eba-1734437739296.png',2),(17,'Fisherman Soup','Vivamus maximus, mi non auctor convallis, neque magna efficitur elit, ac aliquam orci enim quis lectus. Donec commodo ma.',848,35,'Available','images/fisherman_soup-1734437880620.png',1),(18,'Ugu Soup','Aenean vel imperdiet quam, nec molestie tellus. Aliquam volutpat lorem id tincidunt gravida. Phasellus gravida at urna ...',800,59,'Available','images/ugu_soup-1734438560970.jpg',1),(19,'Nsala (White) Soup','Morbi cursus enim vitae orci luctus pharetra quis et lectus. Curabitur pulvinar vel metus vitae scelerisque. Vivamus eu ...',900,50,'Available ','images/nsala_soup-1734438627475.jpg',1);