"""Add user_names column to reviews with default value

Revision ID: 693d3a17f9b0
Revises: 914af26a091c
Create Date: 2025-01-07 16:33:29.924696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693d3a17f9b0'
down_revision = '914af26a091c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_names', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('user_names')

    # ### end Alembic commands ###
